use rocket::serde::{Deserialize, Serialize};
use std::string::ToString;

use crate::resource::game_resource::QUESTION_SECONDS;

///GameProgressDto is used to interact with the game frontend in the [GameResource](crate::resource::game_resource::GameResource)
#[derive(Debug, Default, Clone, Serialize, Deserialize)]
pub struct GameProgressDto {
    pub game_id: String,
    pub current_question: i8,
    pub question_number: i8,
    pub question_content: QuestionDto,
}

///QuestionDto is used to interact with the game frontend in the [GameResource](crate::resource::game_resource::GameResource)
#[derive(Debug, Default, Clone, Serialize, Deserialize)]
pub struct QuestionDto {
    pub question_text: String,
    pub answer_1: String,
    pub answer_2: String,
    pub answer_3: String,
    pub answer_4: String,
    pub good_answer_number: i8,
    pub topic: String,
    pub remaing_time: u64,
}

pub fn questions_java() -> Vec<QuestionDto> {
    vec![
        QuestionDto {
            question_text: "In Java, what type is not a primitive data type ?".to_string(),
            answer_1: "long".to_string(),
            answer_2: "double".to_string(),
            answer_3: "String".to_string(),
            answer_4: "char".to_string(),
            good_answer_number: 3,
            topic: "Java".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "In Java, what statement is true ?".to_string(),
            answer_1: "A class may implement multiple interfaces and may extend one class maximum"
                .to_string(),
            answer_2:
                "A class may implement multiple classes but is allowed to extend only one interface"
                    .to_string(),
            answer_3:
                "A class may implement multiple classes and may implement multiple interfaces"
                    .to_string(),
            answer_4: "A class must implement one interface and must extend one class".to_string(),
            good_answer_number: 1,
            topic: "Java".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
    ]
}

pub fn questions_rust() -> Vec<QuestionDto> {
    vec![QuestionDto {
        question_text: "What is a closure in Rust ?".to_string(),
        answer_1: "A function that is declared in a scope and captures its environment".to_string(),
        answer_2: "An anonymous function that doesn't capture its environment".to_string(),
        answer_3: "A function declared in a scope but doesn't capture its environment".to_string(),
        answer_4: "An anonymous function that captures its environment".to_string(),
        good_answer_number: 4,
        topic: "Rust".to_string(),
        remaing_time: QUESTION_SECONDS,
    }]
}

pub fn questions_kotlin() -> Vec<QuestionDto> {
    vec![
        QuestionDto {
            question_text: "What is Kotlin ?".to_string(),
            answer_1: "A new version of Java".to_string(),
            answer_2: "A JavaScript framework".to_string(),
            answer_3: "A statically-typed programming language for the JVM, Android and browser".to_string(),
            answer_4: "A database management system".to_string(),
            good_answer_number: 3,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "Which platform does Kotlin primarily target ?".to_string(),
            answer_1: "Python Bytecode".to_string(),
            answer_2: "JavaScript".to_string(),
            answer_3: "JVM Bytecode".to_string(),
            answer_4: "PHP".to_string(),
            good_answer_number: 3,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "Are semicolons (;) mandatory at the end of code statements in Kotlin ?".to_string(),
            answer_1: "True".to_string(),
            answer_2: "False".to_string(),
            answer_3: "".to_string(),
            answer_4: "".to_string(),
            good_answer_number: 2,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "What paradigm(s) does the Kotlin programming language follow ?".to_string(),
            answer_1: "Only Object-Oriented".to_string(),
            answer_2: "Procedural".to_string(),
            answer_3: "Only Functional".to_string(),
            answer_4: "Both Object-Oriented and Functional".to_string(),
            good_answer_number: 4,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "How do you declare a variable in Kotlin?".to_string(),
            answer_1: "let myVariable = 10;".to_string(),
            answer_2: "let myVariable: Int = 10".to_string(),
            answer_3: "const myVariable = 10;".to_string(),
            answer_4: "var myVariable: Int = 10".to_string(),
            good_answer_number: 4,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "How do you define a variable in Kotlin that cannot be reassigned ?".to_string(),
            answer_1: "var".to_string(),
            answer_2: "val".to_string(),
            answer_3: "const;".to_string(),
            answer_4: "final".to_string(),
            good_answer_number: 2,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "How do you declare a nullable variable in Kotlin ?".to_string(),
            answer_1: "var name: String?".to_string(),
            answer_2: "var name: String".to_string(),
            answer_3: "var name: String = null".to_string(),
            answer_4: "String name = null".to_string(),
            good_answer_number: 1,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "What is the difference between val and var in Kotlin ?".to_string(),
            answer_1: "They are identical and can be used interchangeably".to_string(),
            answer_2: "'val' declares mutable variables, and 'var' declares immutable ones".to_string(),
            answer_3: "'val' declares immutable variables, and 'var' declares mutable ones".to_string(),
            answer_4: "'val' is used for local variables, and 'var' is used for globak variables".to_string(),
            good_answer_number: 3,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "How do you define a function in Kotlin ?".to_string(),
            answer_1: "fun myFunction() {}".to_string(),
            answer_2: "def myFunction() {}".to_string(),
            answer_3: "function myFunction() {}".to_string(),
            answer_4: "fun = myFunction() {}".to_string(),
            good_answer_number: 1,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "Why is the when expression used in Kotlin ?".to_string(),
            answer_1: "To create a loop".to_string(),
            answer_2: "To define a switch-case statement".to_string(),
            answer_3: "To define a conditional statement".to_string(),
            answer_4: "To create a lambda function".to_string(),
            good_answer_number: 2,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "What does ?. operator do in Kotlin ?".to_string(),
            answer_1: "Null-safe type casting".to_string(),
            answer_2: "Null-sage function calling".to_string(),
            answer_3: "Null-sage member access".to_string(),
            answer_4: "None of the above".to_string(),
            good_answer_number: 3,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "What is the default visibility modifiers in Kotlin if no modifier is specified ?".to_string(),
            answer_1: "public".to_string(),
            answer_2: "private".to_string(),
            answer_3: "internal".to_string(),
            answer_4: "protected".to_string(),
            good_answer_number: 1,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "Which keyword is used to create a singleton in Kotlin ?".to_string(),
            answer_1: "static".to_string(),
            answer_2: "singleton".to_string(),
            answer_3: "single".to_string(),
            answer_4: "object".to_string(),
            good_answer_number: 4,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "What is the main purpose of the let function in Kotlin ?".to_string(),
            answer_1: "To facilitate null checks".to_string(),
            answer_2: "To execute a block of code and return a result".to_string(),
            answer_3: "To transform an object".to_string(),
            answer_4: "None of the above".to_string(),
            good_answer_number: 3,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "Which feature in Kotlin helps to prevent NullPointerExceptions ?".to_string(),
            answer_1: "Safe call operator (?.)".to_string(),
            answer_2: "Non-null Assertion Operator (!!)".to_string(),
            answer_3: "Elvis operator (?:)".to_string(),
            answer_4: "Safe cast operator (as?)".to_string(),
            good_answer_number: 1,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "What is the purpose of the open modifier in Kotlin ?".to_string(),
            answer_1: "It allows a class to be instantiated".to_string(),
            answer_2: "It makes a function available for overriding".to_string(),
            answer_3: "It enforces strict typing for variables".to_string(),
            answer_4: "It allows a function to be called only from within its own class".to_string(),
            good_answer_number: 2,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "How do you create a single-line comment in Kotlin ?".to_string(),
            answer_1: "// This is a comment".to_string(),
            answer_2: "/* This is a comment */".to_string(),
            answer_3: "-- This is a comment".to_string(),
            answer_4: "# This is a comment".to_string(),
            good_answer_number: 1,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "How can we write a multi-line comment in Kotlin ?".to_string(),
            answer_1: "// This is a comment".to_string(),
            answer_2: "/* This is a comment */".to_string(),
            answer_3: "-- This is a comment".to_string(),
            answer_4: "# This is a comment".to_string(),
            good_answer_number: 2,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "What is the role of the init block in Kotlin ?".to_string(),
            answer_1: "To initialize the superclass".to_string(),
            answer_2: "To initialize an object after the constructor has been called".to_string(),
            answer_3: "To initialize static variables".to_string(),
            answer_4: "None of the above".to_string(),
            good_answer_number: 2,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "How do you call a function in Kotlin ?".to_string(),
            answer_1: "functionName()".to_string(),
            answer_2: "call functionName".to_string(),
            answer_3: "Function -> functionName".to_string(),
            answer_4: "functionName:call".to_string(),
            good_answer_number: 1,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "Which Kotlin construct allows a block of code to be executed a specific number of times ?".to_string(),
            answer_1: "for".to_string(),
            answer_2: "while".to_string(),
            answer_3: "repeat".to_string(),
            answer_4: "loop".to_string(),
            good_answer_number: 3,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "Which keyword are used to handle conditional statements in Kotlin ?".to_string(),
            answer_1: "if".to_string(),
            answer_2: "when".to_string(),
            answer_3: "both a and b".to_string(),
            answer_4: "None of the above".to_string(),
            good_answer_number: 3,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "What is the correct way to define a primary constructor in Kotlin ?".to_string(),
            answer_1: "constructor()".to_string(),
            answer_2: "class constructor()".to_string(),
            answer_3: "primary constructor()".to_string(),
            answer_4: "class Person()".to_string(),
            good_answer_number: 4,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "In Kotlin, what is the main purpose of the return keyword ?".to_string(),
            answer_1: "To declare a function".to_string(),
            answer_2: "To create a loop".to_string(),
            answer_3: "To terminate a function and return a value".to_string(),
            answer_4: "To define a class".to_string(),
            good_answer_number: 3,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "What is the primary use of the 'with' function in Kotlin ?".to_string(),
            answer_1: "To create an extension function".to_string(),
            answer_2: "To apply multiple transformations to a collection".to_string(),
            answer_3: "To establish a scope in which an object's properties and functions can be accessed directly without specifying the object's name".to_string(),
            answer_4: "To create an anonymous function".to_string(),
            good_answer_number: 3,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "What does the 'also' function do in Kotlin ?".to_string(),
            answer_1: "It's a scoping function that also executes a block of code".to_string(),
            answer_2: "It runs a block of code and returns the object it was called on".to_string(),
            answer_3: "It runs a block of code and returns the result".to_string(),
            answer_4: "None of the above".to_string(),
            good_answer_number: 2,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "Which of these is not a loop structure in Kotlin ?".to_string(),
            answer_1: "for loop".to_string(),
            answer_2: "while loop".to_string(),
            answer_3: "until loop".to_string(),
            answer_4: "do-while loop".to_string(),
            good_answer_number: 3,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "How do we throw an exception in Kotlin ?".to_string(),
            answer_1: "throw Exception()".to_string(),
            answer_2: "raise Exception()".to_string(),
            answer_3: "Exception.throw()".to_string(),
            answer_4: "None of the above".to_string(),
            good_answer_number: 1,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "What methods can be used to achieve abstraction in Kotlin ?".to_string(),
            answer_1: "Through abstract classes only ?".to_string(),
            answer_2: "Through interfaces only".to_string(),
            answer_3: "Through both abstract classes and interfaces".to_string(),
            answer_4: "None of the above".to_string(),
            good_answer_number: 3,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "How do you declare an array of integers in Kotlin ?".to_string(),
            answer_1: "val numbers = arrayOf(1, 2, 3)".to_string(),
            answer_2: "val numbers = listOf(1, 2, 3)".to_string(),
            answer_3: "val numbers = [1, 2, 3]".to_string(),
            answer_4: "val numbers = Array(3) {0, 1, 2}".to_string(),
            good_answer_number: 1,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "Which of the following is not a basic type in Kotlin ?".to_string(),
            answer_1: "Boolean".to_string(),
            answer_2: "String".to_string(),
            answer_3: "Float".to_string(),
            answer_4: "Char".to_string(),
            good_answer_number: 2,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "How do you declare a String in Kotlin ?".to_string(),
            answer_1: "val str: String = \"Hello World\"".to_string(),
            answer_2: "String str = \"Hello World\"".to_string(),
            answer_3: "val str = String(\"Hello World\")".to_string(),
            answer_4: "String str = new String(\"Hello World\")".to_string(),
            good_answer_number: 1,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "In Kotlin, how do you compare two Strings for equality ?".to_string(),
            answer_1: "str1==srt2".to_string(),
            answer_2: "str1.equals(str2)".to_string(),
            answer_3: "Both a and b".to_string(),
            answer_4: "str1.sameAs(str2)".to_string(),
            good_answer_number: 3,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "Which property can be used to find the length of a string ?".to_string(),
            answer_1: "size".to_string(),
            answer_2: "length".to_string(),
            answer_3: "count".to_string(),
            answer_4: "charCount".to_string(),
            good_answer_number: 2,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "In Kotlin, which collection type has an order and can contain duplicate elements ?".to_string(),
            answer_1: "Set".to_string(),
            answer_2: "List".to_string(),
            answer_3: "Map".to_string(),
            answer_4: "All of the above".to_string(),
            good_answer_number: 2,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "Which function is used to iterate over a collection in Kotlin ?".to_string(),
            answer_1: "forEach()".to_string(),
            answer_2: "for()".to_string(),
            answer_3: "map()".to_string(),
            answer_4: "filter()".to_string(),
            good_answer_number: 1,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "Which of these functions can transform a list in Kotlin ?".to_string(),
            answer_1: "map()".to_string(),
            answer_2: "filter()".to_string(),
            answer_3: "forEach()".to_string(),
            answer_4: "None of the above".to_string(),
            good_answer_number: 1,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "Which collection type ensures element uniqueness in Kotlin ?".to_string(),
            answer_1: "List".to_string(),
            answer_2: "Set".to_string(),
            answer_3: "Map".to_string(),
            answer_4: "MutableList".to_string(),
            good_answer_number: 2,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "How do you create an empty list in Kotlin ?".to_string(),
            answer_1: "emptyList()".to_string(),
            answer_2: "listOf()".to_string(),
            answer_3: "list()".to_string(),
            answer_4: "mutableListOf()".to_string(),
            good_answer_number: 1,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },
        QuestionDto {
            question_text: "What does the mapOf() function do in Kotlin ?".to_string(),
            answer_1: "It creates a new List".to_string(),
            answer_2: "It creates a new Set".to_string(),
            answer_3: "It creates a new Map".to_string(),
            answer_4: "It creates a new Queue".to_string(),
            good_answer_number: 3,
            topic: "Kotlin".to_string(),
            remaing_time: QUESTION_SECONDS,
        },

    ]
}
