on:
  push:
    branches:
      - main

name: Latest Snapshot

jobs:
  containerize:
    name: "Push Docker image to Docker Hub"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3

      - name: "Log in to Docker Hub"
        uses: "docker/login-action@v2"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Extract metadata (tags, labels) for Docker"
        id: "meta"
        uses: "docker/metadata-action@v4"
        with:
          images: "someawesomedockerid/coding-fighters-back"

      - name: "Build and push Docker image"
        uses: "docker/build-push-action@v3"
        with:
          context: .
          push: true
          tags: someawesomedockerid/coding-fighters-back:latest
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: containerize
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            docker stack deploy -c docker-compose.yml coding-fighters
